# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XAO-Base
version:      1.06
version_from: Base.pm
installdirs:  site
requires:
    Error:                         0.13
    Test::Unit:                    0.14

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
